language: haskell

env:
 - GHCVER=7.6.3 CABALVER=1.16
 - GHCVER=7.8.2 CABALVER=1.18
 - GHCVER=head  CABALVER=1.20

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=1.20

befor_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests
 - cabal install hpc-coveralls --force-reinstalls

script:
 - cabal configure --enable-tests --enable-library-coverage
 - cabal build
 - cabal sdist
 - run-cabal-test --show-details=always
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   (cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi)

after_script:
 - ln -s dist/hpc/mix/mono-traversable-0.1.0.0 ./dist/hpc/mix/text
 - hpc-coveralls --exclude-dir=test test